@host=http://localhost
@port=3001
@route=/api

@hostname={{host}}:{{port}}{{route}}

@idUser=622249852c307f3b9b23eef7
@idUserAdmin=622234cfeca18007aa724315
@token=Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjNhNWVlNTljODMwN2IxYTU5ZDM0YTIiLCJpYXQiOjE2NDc5OTI1NjZ9.0nVNJNFdJ8jgY9ur0J0AKZv_aAj8km6duNiHkMXpmes


###  signup
POST {{hostname}}/signup
Content-Type: application/json

{
    "name":"boricua",
    "email":"boricua@email.com",
    "password":"password123"
}


### sign in
POST {{hostname}}/signin
Content-Type: application/json

{
    "email":"boricua@email.com",
    "password":"password123"
}
 
###
GET {{hostname}}/signout

###
GET {{hostname}}/secret/{{idUserAdmin}}
Content-Type: application/json
Authorization: {{token}}


###test
GET {{hostname}}/test
Content-Type: application/json
