@host=http://localhost
@port=3001
@route=/api

@hostname={{host}}:{{port}}{{route}}

@idUser=622234cfeca18007aa724315
@idUserAdmin=623a5ee59c8307b1a59d34a2
@token=Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjNhNWVlNTljODMwN2IxYTU5ZDM0YTIiLCJpYXQiOjE2NDc5OTI1NjZ9.0nVNJNFdJ8jgY9ur0J0AKZv_aAj8km6duNiHkMXpmes

###  create
POST {{hostname}}/category/create/{{idUserAdmin}}
Content-Type: application/json
Authorization: {{token}}

{
    "name":"php"
    
}